version: "3"

services:
    app:
        build:
            context: ./
        volumes:
              - .:/var/www/html
        ports:
            - "8002:80"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true

    database:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1234567890
            MYSQL_PASSWORD: 1234567890
            MYSQL_USER: ewallet
            MYSQL_DATABASE: ewallet
        volumes:
            - $PWD/storage/mysql:/var/lib/mysql
